### ISSUE TITLE
単語登録をしていないユーザーがログイン時エラー

### ISSUE THREAD

**Issue by techiro** [Alesion30/diclog#41]
## 概要
単語が登録されていないためエラーが表示される

![image](https://user-images.githubusercontent.com/35694946/145662054-92466e00-59b9-47c3-b994-77617cbfbbf2.png)

## 解決策
単語がないユーザーには別の画面を表示させる。
- Chrome Extensionのダウンロードを訴求するページ

**Comment by techiro** [comment]
とりあえずエラーがでないようにパッチを当てる
- 単語がない時は仮の単語を表示

**Comment by Alesion30** [comment]
> とりあえずエラーがでないようにパッチを当てる
> 
> * 単語がない時は仮の単語を表示

@techiro 「登録されている単語はありません」的なメッセージを表示してほしいです！
